name = "Lazarus Clause"
author = "iampaycheck"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82ab48e47053dafaa3ceb9ebbd9c600bc0b429a60f525fd4ee244fc1f2a8adba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
